# Generated by Django 5.2.6 on 2025-09-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=255)),
                ('post_title', models.CharField(max_length=255)),
                ('content_file_path', models.CharField(max_length=255)),
                ('visit_count', models.BigIntegerField(default=0)),
                ('create_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('tags', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
